"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowDown, ArrowUpRight, Award, BriefcaseBusiness, CheckCircle2, ChevronRight, Code2, Database, Download, Github, GraduationCap, Linkedin, Mail, Menu, Moon, Sun, X } from "lucide-react";
import { projects, type ProjectCategory } from "@/data/projects";
import { skillGroups } from "@/data/skills";
import { education, experience } from "@/data/experience";
import { certifications } from "@/data/certifications";

const navItems = ["About", "Skills", "Projects", "Experience", "Contact"];
const filters: Array<"All" | ProjectCategory> = ["All", "Data Analytics", "Machine Learning", "QA"];
const fade = { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.15 }, transition: { duration: 0.45 } };

function Header() {
  const [open, setOpen] = useState(false);
  const [dark, setDark] = useState(false);
  useEffect(() => setDark(document.documentElement.classList.contains("dark")), []);
  const toggleTheme = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); };
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-slate-50/90 backdrop-blur-xl dark:border-white/10 dark:bg-navy-950/90">
    <div className="container-page flex h-18 items-center justify-between py-4">
      <a href="#top" className="flex items-center gap-3 font-bold tracking-tight text-navy-950 dark:text-white" aria-label="Palmer Ogiriki, back to top"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-600 text-sm text-white">PO</span><span>Palmer Ogiriki</span></a>
      <nav className="hidden items-center gap-7 md:flex" aria-label="Primary navigation">{navItems.map(item => <a key={item} className="text-sm font-medium text-slate-600 transition hover:text-emerald-600 dark:text-slate-300 dark:hover:text-emerald-400" href={`#${item.toLowerCase()}`}>{item}</a>)}</nav>
      <div className="flex items-center gap-2"><button onClick={toggleTheme} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 bg-white text-navy-950 transition hover:border-emerald-500 dark:border-white/10 dark:bg-navy-900 dark:text-white" aria-label={`Switch to ${dark ? "light" : "dark"} mode`}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 bg-white text-navy-950 md:hidden dark:border-white/10 dark:bg-navy-900 dark:text-white" aria-expanded={open} aria-controls="mobile-nav" aria-label="Toggle navigation">{open ? <X size={20}/> : <Menu size={20}/>}</button></div>
    </div>
    {open && <nav id="mobile-nav" className="container-page border-t border-slate-200 py-3 md:hidden dark:border-white/10" aria-label="Mobile navigation">{navItems.map(item => <a onClick={() => setOpen(false)} key={item} className="block rounded-lg px-3 py-3 text-sm font-medium hover:bg-emerald-500/10 hover:text-emerald-600" href={`#${item.toLowerCase()}`}>{item}</a>)}</nav>}
  </header>;
}

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className="mb-10 max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{copy && <p className="mt-4 leading-7 text-slate-600 dark:text-slate-400">{copy}</p>}</div>; }

function ProjectCard({ project }: { project: (typeof projects)[number] }) { return <article className="card group flex h-full flex-col hover:-translate-y-1 hover:border-emerald-500/40 hover:shadow-soft">
  <div className="mb-5 flex items-start justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">{project.categories.includes("Data Analytics") ? <Database size={21}/> : <Code2 size={21}/>}</div><div className="flex gap-2"><a href={project.github} target="_blank" rel="noopener noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 hover:border-emerald-500 hover:text-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-500 dark:border-white/10" aria-label={`View ${project.title} on GitHub (opens in a new tab)`}><Github size={17}/></a>{project.live && <a href={project.live} target="_blank" rel="noopener noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 hover:border-emerald-500 hover:text-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-500 dark:border-white/10" aria-label={`Open live demo of ${project.title} (opens in a new tab)`}><ArrowUpRight size={17}/></a>}</div></div>
  <h3 className="text-xl font-bold text-navy-950 dark:text-white">{project.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-600 dark:text-slate-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tools.map(tool => <span key={tool} className="rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600 dark:bg-white/5 dark:text-slate-300">{tool}</span>)}</div>
  </article>; }

export function Portfolio() {
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");
  const featured = projects.filter(p => p.featured && (filter === "All" || p.categories.includes(filter)));
  const additional = projects.filter(p => !p.featured && (filter === "All" || p.categories.includes(filter)));
  return <><Header/><main id="top">
    <section className="relative overflow-hidden border-b border-slate-200 pt-28 dark:border-white/10"><div className="container-page grid min-h-[86vh] items-center gap-14 py-16 lg:grid-cols-[1.2fr_.8fr] lg:py-24">
      <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}}><p className="eyebrow">Data • Intelligence • Digital Products</p><h1 className="max-w-4xl text-5xl font-extrabold leading-[1.05] tracking-[-0.045em] text-navy-950 sm:text-6xl lg:text-7xl dark:text-white">Palmer <span className="text-emerald-600 dark:text-emerald-400">Ogiriki</span></h1><p className="mt-5 text-xl font-semibold text-slate-700 sm:text-2xl dark:text-slate-200">Data Analyst, AI and Machine Learning Engineer</p><p className="mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg dark:text-slate-400">I transform data into actionable insights, build intelligent machine-learning solutions and help teams deliver reliable digital products.</p>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="btn-primary">View My Projects <ArrowDown size={17}/></a><a href="/resume-palmer-ogiriki.pdf" className="btn-secondary" download>Download Résumé <Download size={17}/></a><a href="#contact" className="btn-secondary">Contact Me <Mail size={17}/></a><a href="https://github.com/AnalyticPalmer" target="_blank" rel="noopener noreferrer" className="btn-secondary">GitHub Profile <Github size={17}/></a></div></motion.div>
      <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.6,delay:.1}} className="relative mx-auto w-full max-w-md"><div className="aspect-[4/5] overflow-hidden rounded-3xl border border-slate-200 bg-navy-900 p-3 shadow-soft dark:border-white/10"><div className="relative h-full overflow-hidden rounded-2xl border border-white/10 bg-navy-800"><Image src="/profile-photo.jpg" alt="Palmer Ogiriki — Data Analyst, Machine Learning Engineer" fill priority sizes="(max-width: 1024px) min(100vw - 2.5rem, 28rem), 28rem" className="object-cover object-center" /></div></div><div className="absolute -bottom-5 -left-5 rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-soft dark:border-white/10 dark:bg-navy-900"><p className="text-xs uppercase tracking-wider text-slate-500">Based in</p><p className="mt-1 font-semibold text-navy-950 dark:text-white">Abuja, Nigeria</p></div></motion.div>
    </div></section>

    <motion.section {...fade} id="about" className="section-pad"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="About me" title="Analysis that leads to action."/><div className="space-y-5 text-lg leading-8 text-slate-600 dark:text-slate-400"><p>I work across analytics, machine learning and product quality—turning complex information into decisions people can trust.</p><p>My approach combines careful exploration, practical modelling and clear communication. Whether I am building a dashboard, validating a model or supporting a software demonstration, the goal stays the same: reliable work that solves a real problem.</p><div className="grid gap-3 pt-3 sm:grid-cols-2">{["Business-minded analysis","Production-oriented ML","Clear stakeholder reporting","Quality-focused delivery"].map(x => <div key={x} className="flex items-center gap-3 text-sm font-semibold text-navy-950 dark:text-slate-200"><CheckCircle2 className="text-emerald-500" size={18}/>{x}</div>)}</div></div></div></motion.section>

    <motion.section {...fade} id="skills" className="section-pad bg-white dark:bg-navy-900"><div className="container-page"><SectionHeading eyebrow="Core skills" title="A practical, end-to-end toolkit." copy="From raw data to reliable insight, tested models and stakeholder-ready delivery."/><div className="grid gap-5 lg:grid-cols-3">{skillGroups.map((group,i)=><article key={group.title} className="card"><span className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">{i===0?<Database size={21}/>:i===1?<Code2 size={21}/>:<BriefcaseBusiness size={21}/>}</span><h3 className="text-lg font-bold text-navy-950 dark:text-white">{group.title}</h3><div className="mt-5 flex flex-wrap gap-2">{group.items.map(item=><span key={item} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-medium dark:border-white/10">{item}</span>)}</div></article>)}</div></div></motion.section>

    <motion.section {...fade} id="projects" className="section-pad"><div className="container-page"><SectionHeading eyebrow="Selected work" title="Projects built to answer real questions." copy="Explore analytics, machine-learning and quality-focused work. Every claim is grounded in the linked project."/><div className="mb-9 flex flex-wrap gap-2" role="group" aria-label="Filter projects">{filters.map(x=><button key={x} onClick={()=>setFilter(x)} aria-pressed={filter===x} className={`rounded-lg px-4 py-2 text-sm font-semibold transition ${filter===x?"bg-emerald-600 text-white":"border border-slate-200 bg-white text-slate-600 hover:border-emerald-500 dark:border-white/10 dark:bg-navy-900 dark:text-slate-300"}`}>{x}</button>)}</div>{featured.length>0&&<><h3 className="mb-5 text-sm font-bold uppercase tracking-[.16em] text-slate-500">Featured projects</h3><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featured.map(p=><ProjectCard key={p.title} project={p}/>)}</div></>}{additional.length>0&&<><h3 className="mb-5 mt-14 text-sm font-bold uppercase tracking-[.16em] text-slate-500">Additional projects</h3><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{additional.map(p=><ProjectCard key={p.title} project={p}/>)}</div></>}</div></motion.section>

    <motion.section {...fade} id="experience" className="section-pad bg-white dark:bg-navy-900"><div className="container-page"><SectionHeading eyebrow="Experience & education" title="Technical range, business context."/><div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div>{experience.map(job=><article key={job.company} className="card"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><BriefcaseBusiness size={21}/></span><div><h3 className="text-xl font-bold text-navy-950 dark:text-white">{job.company}</h3><p className="mt-1 font-medium text-emerald-600 dark:text-emerald-400">{job.role}</p></div></div><ul className="mt-6 grid gap-3 sm:grid-cols-2">{job.responsibilities.map(r=><li key={r} className="flex gap-3 text-sm leading-6"><ChevronRight className="mt-1 shrink-0 text-emerald-500" size={16}/>{r}</li>)}</ul></article>)}</div><div className="space-y-6">{education.map(item=><article key={item.field} className="card"><GraduationCap className="text-emerald-500"/><p className="mt-4 text-sm font-semibold text-emerald-600 dark:text-emerald-400">{item.qualification}</p><h3 className="mt-1 font-bold text-navy-950 dark:text-white">{item.field}</h3></article>)}</div></div></div></motion.section>

    <motion.section {...fade} id="certifications" className="section-pad"><div className="container-page"><SectionHeading eyebrow="Credentials" title="Certifications"/><div className="max-w-2xl">{certifications.map(c=><article key={c.name} className="card flex items-center gap-5"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><Award size={23}/></span><div><p className="text-sm text-slate-500">{c.issuer}</p><h3 className="font-bold text-navy-950 dark:text-white">{c.name}</h3></div></article>)}</div></div></motion.section>

    <motion.section {...fade} id="contact" className="section-pad border-y border-slate-200 bg-navy-950 text-white dark:border-white/10"><div className="container-page grid items-end gap-10 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">Let’s work together</p><h2 className="max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">Have a data, machine-learning or digital product challenge?</h2><p className="mt-5 max-w-2xl leading-7 text-slate-400">I’m open to professional opportunities, project conversations and thoughtful collaborations.</p></div><a href="mailto:ogirikipalmerc@gmail.com" className="btn-primary">Start a conversation <Mail size={18}/></a></div><div className="container-page mt-12 flex flex-wrap gap-3"><a className="btn-secondary border-white/15 bg-white/5 text-white" href="mailto:ogirikipalmerc@gmail.com"><Mail size={17}/> Email</a><a className="btn-secondary border-white/15 bg-white/5 text-white" href="https://github.com/AnalyticPalmer" target="_blank" rel="noopener noreferrer"><Github size={17}/> GitHub</a><a className="btn-secondary border-white/15 bg-white/5 text-white" href="https://www.linkedin.com/in/palmerogiriki/" target="_blank" rel="noopener noreferrer" aria-label="Visit Palmer Ogiriki on LinkedIn (opens in a new tab)"><Linkedin size={17}/> LinkedIn</a></div></motion.section>
  </main><footer className="bg-navy-950 py-8 text-slate-400"><div className="container-page flex flex-col gap-3 text-sm sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Palmer Ogiriki. All rights reserved.</p><p>Data Analyst • AI & Machine Learning Engineer</p></div></footer></>;
}
